version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
  pre_build:
    commands:
      - echo Installing dependencies...
      - bundle install
      - echo Installing and setting up webpack with yarn
      - bundle exec rake webpacker:install
      - echo Verifying if Node.js is installed
      - bundle exec rake webpacker:check_node
      - echo Verifying if yarn is installed
      - bundle exec rake webpacker:check_yarn
      - echo Installing all Javascript dependencies as specified via Yarn
      - bundle exec rake webpacker:yarn_install

  build:
    commands:
      - echo Building assets
      - bundle exec rails webpacker:compile
      - rm -rf node_modules
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
